version: '2'
services:
    jhipstersample-app:
        image: jhipstersample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersample-mysql:3306/jhipstersample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersample-mysql:
        extends:
            file: mysql.yml
            service: jhipstersample-mysql
